"""created department and employee tables

Revision ID: 5fe57aa6a3
Revises: 
Create Date: 2018-10-30 14:48:58.226373

"""

# revision identifiers, used by Alembic.
revision = '5fe57aa6a3'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('employee',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('Employee_id', sa.String(), nullable=False),
    sa.Column('Employee_Name', sa.String(), nullable=True),
    sa.Column('Hired_On', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], name='Department id'),
    sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('department')
    ### end Alembic commands ###
